export const animals = [
    {
        id: '1',
        name: 'Betsy the Cow',
        type: 'cow',
        says: 'Mooooooo!',
        top: '200px',
        left: '50%',
    },
    {
        id: '2',
        name: 'Noel the Donkey',
        type: 'donkey',
        says: 'Heee haw!',
        top: '315px',
        left: '38%',
    },
    {
        id: '3',
        name: 'Golly the Goose',
        type: 'goose',
        says: 'Run pig! Be free! I would if I could.',
        top: '370px',
        left: '65%',
    },
    {
        id: '4',
        name: 'Wilbur the Pig',
        type: 'pig',
        says: 'You have been my friend. That in itself is a tremendous thing.',
        top: '310px',
        left: '5%',
    },
    {
        id: '5',
        name: 'Charlotte the Spider',
        type: 'spider',
        says: 'Never hurry and never worry!',
        top: '260px',
        left: '72%',
    },
    {
        id: '6',
        name: 'Samuel the Sheep',
        type: 'sheep',
        says: "Just because we're sheep, it doesn't mean we have to follow. Think for yourselves.",
        top: '225px',
        left: '20%',
    },
];
